### ISSUE TITLE
RTR Flaps between RPKI-Prover and IOS-XR Router

### ISSUE THREAD

**Issue by rencarlo014** [lolepezy/rpki-prover#215]
Good day!

We are trying to integrate our Cisco IOS-XR Router to RPKI server (RPKI-Prover), but we noticed that the RTR between the RPKI-Prover and IOS-XR router is flapping every 20-30 seconds. Any recommendations on how we can fix this? You may refer on the details below:

Information from Cisco ASR9K Router:
```
RP/0/RSP0/CPU0:ROUTER#show bgp rpki server summary
Fri Aug  9 13:31:00.563 UTC

Hostname/Address        Transport       State           Time            ROAs (IPv4/IPv6)
x.x.x.x                 TCP:3323       ESTAB           00:00:03        58883/11601
y.y.y.y                 TCP:3323       ESTAB           00:00:25        101549/17541
!
RP/0/RSP0/CPU0:ROUTER#show bgp rpki server summary
Fri Aug  9 13:31:17.060 UTC

Hostname/Address        Transport       State           Time            ROAs (IPv4/IPv6)
x.x.x.x                 TCP:3323        NONE            00:00:04        N/A
y.y.y.y                 TCP:3323        ESTAB           00:00:03        0/34393
!
RP/0/RSP0/CPU0:ROUTER#show bgp rpki server summary
Fri Aug  9 13:31:32.503 UTC

Hostname/Address        Transport       State           Time            ROAs (IPv4/IPv6)
x.x.x.x                 TCP:3323        ESTAB           00:00:10        219244/38018
y.y.y.y                 TCP:3323        ESTAB           00:00:18        201417/35529
!
RP/0/RSP0/CPU0:ROUTER#show bgp rpki server x.x.x.x
Fri Aug  9 13:32:01.927 UTC

RPKI Cache-Server x.x.x.x
  Transport: TCP port 3323
  Connect state: CONNECT
  Conn attempts: 1
  Total byte RX: 0
  Total byte TX: 0
  Last reset
    Timest: Aug 09 13:31:37 (00:00:25 ago)
    Reason: protocol error
RPKI-RTR protocol information
  Serial number: 0
  Cache nonce: 0xA7B8
  Protocol state: NONE
  Refresh  time: 3600 seconds
  Response time: 600 seconds
  Purge time: 60 seconds
  Protocol exchange
    ROAs announced: 484664 IPv4  115647 IPv6
    ROAs withdrawn:      0 IPv4       0 IPv6
    Error Reports :      0 sent       0 rcvd
  Last protocol error
    Reason: invalid message type
    Detail: invalid message type '9'
!
RP/0/RSP0/CPU0:ROUTER#show logg last 20
Fri Aug  9 13:32:21.259 UTC

Log Buffer (2097152 bytes):

RP/0/RSP0/CPU0:2024 Aug  9 13:30:04.281 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : y.y.y.y UP
RP/0/RSP0/CPU0:2024 Aug  9 13:30:08.028 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : x.x.x.x UP
RP/0/RSP0/CPU0:2024 Aug  9 13:30:28.348 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : x.x.x.x DOWN (invalid message type '9')
RP/0/RSP0/CPU0:2024 Aug  9 13:30:30.397 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : y.y.y.y DOWN (invalid message type '9')
RP/0/RSP0/CPU0:2024 Aug  9 13:30:31.196 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : x.x.x.x UP
RP/0/RSP0/CPU0:2024 Aug  9 13:30:35.278 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : y.y.y.y UP
RP/0/RSP0/CPU0:2024 Aug  9 13:30:54.824 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : x.x.x.x DOWN (invalid message type '9')
RP/0/RSP0/CPU0:2024 Aug  9 13:30:57.200 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : x.x.x.x UP
RP/0/RSP0/CPU0:2024 Aug  9 13:31:11.254 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : y.y.y.y DOWN (invalid message type '9')
RP/0/RSP0/CPU0:2024 Aug  9 13:31:13.311 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : x.x.x.x DOWN (invalid message type '9')
RP/0/RSP0/CPU0:2024 Aug  9 13:31:14.047 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : y.y.y.y UP
RP/0/RSP0/CPU0:2024 Aug  9 13:31:22.181 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : x.x.x.x UP
RP/0/RSP0/CPU0:2024 Aug  9 13:31:37.148 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : x.x.x.x DOWN (invalid message type '9')
RP/0/RSP0/CPU0:2024 Aug  9 13:31:39.680 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : y.y.y.y DOWN (invalid message type '9')
RP/0/RSP0/CPU0:2024 Aug  9 13:31:40.261 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : y.y.y.y UP
RP/0/RSP0/CPU0:2024 Aug  9 13:31:52.607 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : y.y.y.y DOWN (invalid message type '9')
RP/0/RSP0/CPU0:2024 Aug  9 13:31:53.588 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : y.y.y.y UP
RP/0/RSP0/CPU0:2024 Aug  9 13:32:03.506 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : x.x.x.x UP
RP/0/RSP0/CPU0:2024 Aug  9 13:32:16.613 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : y.y.y.y DOWN (invalid message type '9')
RP/0/RSP0/CPU0:2024 Aug  9 13:32:17.629 UTC: bgp[1066]: %ROUTING-BGP-5-RPKI_ADJCHANGE : y.y.y.y UP
```

NOTE: x.x.x.x is rpki-prover1 IP address and y.y.y.y is rpki-prover2 IP address.

Information from RPKI-Prover (RHEL9 hosted in VMware ESXi):
```
[root@RPKIPROVER001 ~]# sestatus
SELinux status:                 disabled
[root@RPKIPROVER001 ~]# systemctl status rpki-prover.service
● rpki-prover.service - RPKI Prover
     Loaded: loaded (/etc/systemd/system/rpki-prover.service; enabled; preset: disabled)
     Active: active (running) since Fri 2024-08-09 13:25:09 PST; 16min ago
   Main PID: 208378 (rpki-prover)
      Tasks: 29 (limit: 100365)
     Memory: 585.9M
        CPU: 56.225s
     CGroup: /system.slice/rpki-prover.service
             ├─208378 /usr/local/bin/rpki-prover --with-rtr --rtr-address 0.0.0.0 --rtr-port 3323 --rpki-root-directory /etc/rpki-prover
             ├─211408 /usr/local/bin/rpki-prover --worker version:1723182058471785509:rrdp-fetch:https://rpki.netiface.net/rrdp/notification.xml +RTS -I0 -N1 -A20m -AL64m -M10>
             └─211418 /usr/local/bin/rpki-prover --worker version:1723182058471785509:rrdp-fetch:https://rpki.luys.cloud/rrdp/notification.xml +RTS -I0 -N1 -A20m -AL64m -M1024>

Aug 09 13:41:14 RPKIPROVER001 rpki-prover[208378]: Info    [pid 208378]      2024-08-09 05:41:14.396Z  Fetching rsync://rsync.rpki.tianhai.link/repo/TianhaiRpki/3.
Aug 09 13:41:16 RPKIPROVER001 rpki-prover[208378]: Info    [pid 211353]      2024-08-09 05:41:16.775Z  Finished rsynching rsync://rsync.rpki.co/rpki/rsync/0 to /etc/>
Aug 09 13:41:16 RPKIPROVER001 rpki-prover[208378]: Info    [pid 208378]      2024-08-09 05:41:16.784Z  Fetched rsync://rsync.rpki.co/rpki/rsync/0, took 7563ms.
Aug 09 13:41:16 RPKIPROVER001 rpki-prover[208378]: Info    [pid 208378]      2024-08-09 05:41:16.784Z  Fetching rsync://rsync.rpki.tianhai.link/repo/TianhaiRpki/0.
Aug 09 13:41:17 RPKIPROVER001 rpki-prover[208378]: Info    [pid 208378]      2024-08-09 05:41:17.774Z  Fetching rsync://krill.ca-bc-01.ssmidge.xyz/repo/SsmidgeLLC/1.
Aug 09 13:41:18 RPKIPROVER001 rpki-prover[208378]: Info    [pid 211363]      2024-08-09 05:41:18.214Z  Finished rsynching rsync://rpki.co/repo to /etc/rpki-prover/rs>
Aug 09 13:41:18 RPKIPROVER001 rpki-prover[208378]: Info    [pid 208378]      2024-08-09 05:41:18.363Z  Fetched rsync://rpki.co/repo, took 9077ms.
Aug 09 13:41:18 RPKIPROVER001 rpki-prover[208378]: Info    [pid 208378]      2024-08-09 05:41:18.363Z  Fetching rsync://krill.ca-bc-01.ssmidge.xyz/repo/SsmidgeLLC/0.
Aug 09 13:41:19 RPKIPROVER001 rpki-prover[208378]: Info    [pid 208378]      2024-08-09 05:41:19.420Z  Fetching rsync://krill.ca-bc-01.ssmidge.xyz/repo/AS199177/0.
Aug 09 13:41:26 RPKIPROVER001 rpki-prover[208378]: Info    [pid 208378]      2024-08-09 05:41:26.366Z  Closing connection with z.z.z.z:53152

[root@RPKIPROVER001 ~]#
[root@TPZ-RPKI-RPKICLIENT-001 ~]# netstat -an
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:3323            0.0.0.0:*               LISTEN
tcp        0  57912 x.x.x.x:3323            z.z.z.z:52285     ESTABLISHED

[root@RPKIPROVER001 ~]# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: ens34
  sources:
  services: cockpit dhcpv6-client ssh
  ports: 3323/tcp
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

```

Any idea how we can resolve this issue between RPKI Prover and Cisco IOS-XR router? Please also take note that there are no firewalls between RPKI prover and Cisco IOS-XR router.

Thank you,
Ren

**Comment by lolepezy** [comment]
Thanks for the detailed report!

A couple of things not directly relevant to your specific issue.
1) ` --rpki-root-directory /etc/rpki-prover` is probably not what you wanted? rpki-prover will write a few Gbs of data in the directory set by `--rpki-root-directory` but my understanding of the current Linux convention (which may be off) is that `/etc` should stay read-only. That may also result in errors in case rpki-prover can't actually write anything there. Could you send me `ls -Rl /etc/rpki-prover/*`? So probably, something like ` --rpki-root-directory /var/lib/rpki-prover` is more conventional way of doing it. 

2) Could you run it with `--log-level debug` and post here the log? It will contain some IP addresses in case it's a privacy concern for you. There's also on option to set something like `--rtr-log /var/log/rpki-prover-rtr.log` to have a separate log for RTR protocol.

To the issue at hands. My assumption is that `invalid message type '9'` means the RTR PDU type 9 which is a router key (https://datatracker.ietf.org/doc/html/rfc8210.html#section-5.10). Most like that means the router only supports RTR version 0 not including router keys. That means it's a bug in rpki-prover which sends RTR version 1 packages to a connection that only supports RTR v0. That can be fixed pretty quickly, but if it's possible to enable version 1 support at the router side it should fix the issue for you.

**Comment by lolepezy** [comment]
I've published a release that should/might solve the issue
https://github.com/lolepezy/rpki-prover/releases/tag/v0.9.5

**Comment by rencarlo014** [comment]
Hello, @lolepezy. Thank you so much for the detailed explanation! It gives me an idea how RTR really works. Regarding on your inquiries, you may refer below:

> 1. ` --rpki-root-directory /etc/rpki-prover` is probably not what you wanted? rpki-prover will write a few Gbs of data in the directory set by `--rpki-root-directory` but my understanding of the current Linux convention (which may be off) is that `/etc` should stay read-only. That may also result in errors in case rpki-prover can't actually write anything there. Could you send me `ls -Rl /etc/rpki-prover/*`? So probably, something like ` --rpki-root-directory /var/lib/rpki-prover` is more conventional way of doing it.

-I'm sorry, I'm not really into Linux. rpki-prover has been installed by my colleague. For the output of `ls-RI /etc/rpki-prover/*`, please see the attached .txt file.
[08112024_ls -RI_RPKIPROVER001.txt](https://github.com/user-attachments/files/16570167/08112024_ls.-RI_RPKIPROVER001.txt)

**NOTE: Some output has been omitted.** 

> 2. Could you run it with `--log-level debug` and post here the log? It will contain some IP addresses in case it's a privacy concern for you. There's also on option to set something like `--rtr-log /var/log/rpki-prover-rtr.log` to have a separate log for RTR protocol.

-I'm trying to change the logging severity to debug using the command `rpki-prover --log-level debug` and got the following error:
```
[root@RPKIPROVER001 ~]# rpki-prover --log-level debug
Debug   [pid 204689]      2024-08-10 16:10:17.421Z  Starting rpki-prover-0.9.3.
Info    [pid 204689]      2024-08-10 16:10:17.424Z  Root directory is not set, using defaul ${HOME}/.rpki
Error   [pid 204689]      2024-08-10 16:10:17.424Z  Couldn't initialise, problems: ValidationState {validations = Validations (fromList []), topDownMetric = RawMetric {rsyncMetrics = MetricMap {unMetricMap = MonoidalMap {getMonoidalMap = fromList []}}, rrdpMetrics = MetricMap {unMetricMap = MonoidalMap {getMonoidalMap = fromList []}}, validationMetrics = MetricMap {unMetricMap = MonoidalMap {getMonoidalMap = fromList []}}, vrpCounts = VrpCounts {totalUnique = 0, perTaUnique = MonoidalMap {getMonoidalMap = fromList []}}}, traces = fromList []}.
```

> To the issue at hands. My assumption is that `invalid message type '9'` means the RTR PDU type 9 which is a router key (https://datatracker.ietf.org/doc/html/rfc8210.html#section-5.10). Most likely that means the router only supports RTR version 0 not including router keys. That means it's a bug in rpki-prover which sends RTR version 1 packages to a connection that only supports RTR v0. That can be fixed pretty quickly, but if it's possible to enable version 1 support at the router side it should fix the issue for you.

-Regarding on this part `but if it's possible to enable version 1 support at the router side it should fix the issue for you.`, I'm still trying to do some research on how to enable the RTR version 1 on Cisco IOS-XR router, but currently no luck. Will update you once I found a way how to configure the RTR version on IOS-XR router.

Thank you so much,
Ren

**Comment by rencarlo014** [comment]
> I've published a release that should/might solve the issue https://github.com/lolepezy/rpki-prover/releases/tag/v0.9.5

Hello again, @lolepezy. This is maybe an off-topic, but is there anyway you can guide me on how can I update/upgrade the rpki-prover without doing reinstallation?

I will also try to simulate the newer version on my lab environment and will provide feedback.

Thank you,
Ren

**Comment by lolepezy** [comment]
> I'm not really into Linux. rpki-prover has been installed by my colleague. For the output of ls-RI /etc/rpki-prover/*, please see the attached .txt file.

Thanks! From what I can see it works fine so I guess it's okay to just leave `--rpki-root-directory /etc/rpki-prover` as is.

> I'm trying to change the logging severity to debug using the command rpki-prover --log-level debug and got the following error:

I meant you can add `--log-level debug` to the existing command line parameters for more detailed logging.

> This is maybe an off-topic, but is there any way you can guide me on how can I update/upgrade the rpki-prover without doing reinstallation?

The release (https://github.com/lolepezy/rpki-prover/releases/tag/v0.9.5) contains statically linked Linux binary, it would be the easiest to download it and replace the current one with it, nothing else is needed.

**Comment by lolepezy** [comment]
> Regarding on this part but if it's possible to enable version 1 support at the router side it should fix the issue for you., I'm still trying to do some research on how to enable the RTR version 1 on Cisco IOS-XR router, but currently no luck. Will update you once I found a way how to configure the RTR version on IOS-XR router.

The release 0.9.5 should fix the issue with protocol version, so it would be the simplest to just try the release so you wouldn't have to do anything with the router setup.

**Comment by rencarlo014** [comment]
> Thanks! From what I can see it works fine so I guess it's okay to just leave `--rpki-root-directory /etc/rpki-prover` as is.

Yes, but as you've suggested, what I did is move the root directory on /var/lib/.

> I meant you can add `--log-level debug` to the existing command line parameters for more detailed logging.

When I tried to add the `--log-level debug`, I am encountering the error, but we can skip this for now.

> The release (https://github.com/lolepezy/rpki-prover/releases/tag/v0.9.5) contains statically linked Linux binary, it would be the easiest to download it and replace the current one with it, nothing else is needed.

Can you check the following procedures? What I did is to remove the necessary directories and rebuild from start using the `./build-local.sh` from v0.9.5.

```
!
sudo systemctl stop rpki-prover.service
sudo systemctl disable rpki-prover.service
sudo systemctl status rpki-prover.service
!
cd /etc/systemd/system/
ls -l | grep rpki
rm -rf rpki-prover.service
!
cd /usr/local/bin/
ls -l | grep rpki
rm -rf rpki-prover
!
cd /var/lib/
ls -l | grep rpki
rm -rf rpki-prover
!
cd ~
git clone https://github.com/lolepezy/rpki-prover.git
!
cd rpki-prover
./build-local.sh
!
stack install rpki-prover:rpki-prover
!
sudo ./mkdirs.sh /var/lib/rpki-prover
!
sudo mv /root/.local/bin/rpki-prover /usr/local/bin/rpki-prover
!
sudo nano /etc/systemd/system/rpki-prover.service
###
[Unit]
Description=RPKI Prover
Wants=network-online.target
After=network-online.target

[Service]
User=root
Group=root
Type=simple
ExecStart=/usr/local/bin/rpki-prover --with-rtr --rtr-address 0.0.0.0 --rtr-port 3323 --rpki-root-directory /var/lib/rpki-prover

[Install]
WantedBy=multi-user.target
###
!
sudo systemctl enable rpki-prover.service
sudo systemctl start rpki-prover.service
sudo systemctl status rpki-prover.service
```

Thank you,
Ren

**Comment by rencarlo014** [comment]
> The release 0.9.5 should fix the issue with protocol version, so it would be the simplest to just try the release so you wouldn't have to do anything with the router setup.

Yes, I've simulated v0.9.5 on my lab environment. It worked like a charm. The following is the result of the simulation:

**Informations from RPKI Prover:**
```
[root@localhost rpki-prover]# sudo systemctl status rpki-prover.service
● rpki-prover.service - RPKI Prover
     Loaded: loaded (/etc/systemd/system/rpki-prover.service; enabled; preset: disabled)
     Active: active (running) since Sun 2024-08-11 15:29:05 PST; 5h 44min ago
   Main PID: 284350 (rpki-prover)
      Tasks: 24 (limit: 65134)
     Memory: 1.1G
        CPU: 19min 6.408s
     CGroup: /system.slice/rpki-prover.service
             ├─284350 /usr/local/bin/rpki-prover --with-rtr --rtr-address 0.0.0.0 --rtr-port 3323 --rpki-root-directory /var/lib/rpki-prover
             └─312932 /usr/local/bin/rpki-prover --worker version:1723381945797879037:rrdp-fetch:https://rpki.netiface.net/rrdp/notificatio>

Aug 11 21:12:33 localhost.localdomain rpki-prover[284350]: rsync error: error in socket IO (code 10) at clientserver.c(138) [Receiver=3.2.3]
Aug 11 21:12:33 localhost.localdomain rpki-prover[284350]: ,
Aug 11 21:12:33 localhost.localdomain rpki-prover[284350]:                                             stdout =
Aug 11 21:12:33 localhost.localdomain rpki-prover[284350]: Error   [pid 313009]      2024-08-11 13:12:33.349Z  Rsync process failed: Raw co>
Aug 11 21:12:33 localhost.localdomain rpki-prover[284350]:  
Aug 11 21:12:33 localhost.localdomain rpki-prover[284350]:                                             with code 10,
Aug 11 21:12:33 localhost.localdomain rpki-prover[284350]:                                             stderr = rsync: [Receiver] failed to>
Aug 11 21:12:33 localhost.localdomain rpki-prover[284350]: rsync error: error in socket IO (code 10) at clientserver.c(138) [Receiver=3.2.3]
Aug 11 21:12:33 localhost.localdomain rpki-prover[284350]: ,
Aug 11 21:12:33 localhost.localdomain rpki-prover[284350]:                                             stdout =
[root@localhost rpki-prover]#
[root@localhost rpki-prover]# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:9999            0.0.0.0:*               LISTEN      284350/rpki-prover  
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      930/sshd: /usr/sbin 
tcp        0      0 0.0.0.0:3323            0.0.0.0:*               LISTEN      284350/rpki-prover  
[root@localhost rpki-prover]#
[root@localhost rpki-prover]# ifconfig ens160
ens160: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.86.129  netmask 255.255.255.0  broadcast 192.168.86.255
        inet6 fe80::20c:29ff:fe80:ce16  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:80:ce:16  txqueuelen 1000  (Ethernet)
        RX packets 2212692  bytes 142854681 (136.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2697044  bytes 3473070145 (3.2 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Information from Cisco IOS-XR Router:**
```
RP/0/0/CPU0:XRv8(config-bgp-rpki-server)#do show bgp rpki server summary       
Sun Aug 11 13:15:44.448 UTC

Hostname/Address        Transport       State           Time            ROAs (IPv4/IPv6)
192.168.86.129          TCP:3323        ESTAB           05:47:08        484691/115598
RP/0/0/CPU0:XRv8(config-bgp-rpki-server)#
RP/0/0/CPU0:XRv8(config-bgp-rpki-server)#do show bgp rpki server 192.168.86.129
Sun Aug 11 13:16:23.845 UTC

RPKI Cache-Server 192.168.86.129
  Transport: TCP port 3323
  Connect state: ESTAB
  Conn attempts: 1
  Total byte RX: 9355004
  Total byte TX: 600
  Last reset
    Timest: Aug 11 07:28:34 (05:47:49 ago)
    Reason: read error
RPKI-RTR protocol information
  Serial number: 50
  Cache nonce: 0x66FA
  Protocol state: DATA_END
  Refresh  time: 3600 seconds
  Response time: 600 seconds
  Purge time: 60 seconds
  Protocol exchange
    ROAs announced: 484773 IPv4  115629 IPv6
    ROAs withdrawn:     82 IPv4      31 IPv6
    Error Reports :      0 sent       0 rcvd
```

Thank you so much for your assistance, @lolepezy.

**Comment by rencarlo014** [comment]
Hello, @lolepezy. Here is the summary for the conducted testing and simulation on a lab environment.

**Actions Taken:**
1. Installed the RPKI Prover v0.9.4:
```
!
sudo yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
sudo yum config-manager --enable epel
sudo yum repolist
sudo yum update
sudo yum install rsync lmdb-devel zlib-devel expat-devel xz-devel gmp-devel
!
sudo yum install https://dl.fedoraproject.org/pub/archive/epel/7/aarch64/Packages/e/epel-release-7-12.noarch.rpm
sudo yum config-manager --enable epel
sudo yum repolist
sudo yum update
sudo yum install rsync lmdb-devel zlib-devel expat-devel xz-devel gmp-devel
!
curl -sSL https://get.haskellstack.org/ | sh
sudo wget https://github.com/lolepezy/rpki-prover/archive/refs/tags/v0.9.4.tar.gz
tar xvzf v0.9.4.tar.gz
cd rpki-prover-0.9.4
!
./build-local.sh
!
stack install rpki-prover:rpki-prover
sudo ./mkdirs.sh /var/lib/rpki-prover
!
sudo mv /root/.local/bin/rpki-prover /usr/local/bin/rpki-prover
!
sudo nano /etc/systemd/system/rpki-prover.service
###
[Unit]
Description=RPKI Prover
Wants=network-online.target
After=network-online.target

[Service]
User=root
Group=root
Type=simple
ExecStart=/usr/local/bin/rpki-prover --with-rtr --rtr-address 0.0.0.0 --rtr-port 3323 --rpki-root-directory /var/lib/rpki-prover

[Install]
WantedBy=multi-user.target
###
!
sudo systemctl start rpki-prover.service
!
[root@localhost ~]# rpki-prover --version
rpki-prover-0.9.4
!
```

2. Integrated Cisco IOS-XR router to RPKI Prover v0.9.4:
```
!
router bgp <ASN>
 !
 rpki server 192.168.86.132
  transport tcp port 3323
  refresh-time 3600
  response-time 600
!
```

3. Validated that the RTR issue still persists using RPKI Prover v0.9.4:
```
!
RP/0/0/CPU0:XRv8(config-bgp-rpki-server)#do show bgp rpki server summary
Sun Aug 11 17:08:15.482 UTC

Hostname/Address        Transport       State           Time            ROAs (IPv4/IPv6)
192.168.86.132          TCP:3323        ESTAB           00:01:23        479044/114458

RP/0/0/CPU0:XRv8(config-bgp-rpki-server)#
RP/0/0/CPU0:XRv8(config-bgp-rpki-server)#do show bgp rpki server summary
Sun Aug 11 17:08:16.302 UTC

Hostname/Address        Transport       State           Time            ROAs (IPv4/IPv6)
192.168.86.132          TCP:3323        NONE            00:00:00        N/A

RP/0/0/CPU0:XRv8(config-bgp-rpki-server)#do show bgp rpki server summary
Sun Aug 11 17:08:18.052 UTC

Hostname/Address        Transport       State           Time            ROAs (IPv4/IPv6)
192.168.86.132          TCP:3323        ESTAB           00:00:00        2508/975

RP/0/0/CPU0:XRv8(config-bgp-rpki-server)#do show logg last 20
Sun Aug 11 17:09:38.286 UTC
<output omitted for brevity>
RP/0/0/CPU0:Aug 11 17:06:51.968 : bgp[1052]: %ROUTING-BGP-5-RPKI_ADJCHANGE : 192.168.86.132 UP  
RP/0/0/CPU0:Aug 11 17:08:15.802 : bgp[1052]: %ROUTING-BGP-5-RPKI_ADJCHANGE : 192.168.86.132 DOWN (invalid message type '9') 
RP/0/0/CPU0:Aug 11 17:08:17.302 : bgp[1052]: %ROUTING-BGP-5-RPKI_ADJCHANGE : 192.168.86.132 UP  
RP/0/0/CPU0:Aug 11 17:09:38.046 : bgp[1052]: %ROUTING-BGP-5-RPKI_ADJCHANGE : 192.168.86.132 DOWN (invalid message type '9') 
!
```

4. Upgraded the RPKI Prover from v0.9.4 to v0.9.5:
```
!
rpki-prover --version
!
sudo wget https://github.com/lolepezy/rpki-prover/releases/download/v0.9.5/rpki-prover-static
ls -l | grep rpki
!
sudo systemctl stop rpki-prover.service
sudo systemctl status rpki-prover.service
!
ls -l /usr/local/bin/ | grep rpki
sudo mv /usr/local/bin/rpki-prover /usr/local/bin/rpki-prover.bak
ls -l /usr/local/bin/ | grep rpki
sudo mv rpki-prover-static /usr/local/bin/rpki-prover
chmod +x /usr/local/bin/rpki-prover
ls -l /usr/local/bin/ | grep rpki
!
sudo systemctl start rpki-prover.service
sudo systemctl status rpki-prover.service
!
rpki-prover --version
!
[root@localhost ~]# rpki-prover --version
rpki-prover-0.9.5
!
```

5. Validated that the RTR flaps between Cisco IOS-XR Router and RPKI Prover has been resolved after the upgrade from v0.9.4 to v0.9.5:
```
!
RP/0/0/CPU0:XRv8(config-bgp-rpki-server)#do show bgp rpki server summary
Sun Aug 11 21:20:59.303 UTC

Hostname/Address        Transport       State           Time            ROAs (IPv4/IPv6)
192.168.86.132          TCP:3323        ESTAB           04:07:00        480263/115120
!
RP/0/0/CPU0:XRv8(config-bgp-rpki-server)#do show bgp rpki server 192.168.86.132
Sun Aug 11 21:21:37.321 UTC

RPKI Cache-Server 192.168.86.132
  Transport: TCP port 3323
  Connect state: ESTAB
  Conn attempts: 1
  Total byte RX: 13750296
  Total byte TX: 428
  Last reset
    Timest: Aug 11 17:12:18 (04:09:19 ago)
    Reason: protocol error
RPKI-RTR protocol information
  Serial number: 36
  Cache nonce: 0x61A4
  Protocol state: DATA_END
  Refresh  time: 3600 seconds
  Response time: 600 seconds
  Purge time: 60 seconds
  Protocol exchange
    ROAs announced: 487934 IPv4  117514 IPv6
    ROAs withdrawn:   7671 IPv4    2394 IPv6
    Error Reports :      0 sent       0 rcvd
  Last protocol error
    Reason: received error-report
    Detail: received error-report: no data available
!
```

To conclude, after the commit #216 and upgrade of RPKI-Prover from v0.9.4 to v0.9.5, the issue was resolved. Just to add, I've already implemented this to the production and the RTR is now stable. Big thanks to you @lolepezy for providing assistance regarding on this matter. 

Best regards,
Ren

**Comment by lolepezy** [comment]
> Can you check the following procedures? What I did is to remove the necessary directories and rebuild from start using the ./build-local.sh from v0.9.5. 

Your procedure looks good to me.

> Is there an easy way to do it? Than rebuilding rpki-prover from scratch

Currently, the only options are 
- static Linux binary
- Docker image
- Building from sources
There're plans to have DEB and RPM packages but it is not implemented yet.

And thanks for the detailed bug report, it allowed me to fix the bug very quickly, much appreciated!

**Comment by rencarlo014** [comment]
> Your procedure looks good to me.

Thank you, I've used the static linux binary that you've uploaded for v0.9.5.

> Currently, the only options are
> 
> * static Linux binary
> * Docker image
> * Building from sources
>   There're plans to have DEB and RPM packages but it is not implemented yet.

I see, looking forward to it.

> And thanks for the detailed bug report, it allowed me to fix the bug very quickly, much appreciated!

It is my pleasure, @lolepezy. By the way, is there a roadmap for RPKI-Prover to support BGPsec?

Thanks,
Ren

**Comment by lolepezy** [comment]
> By the way, is there a roadmap for RPKI-Prover to support BGPsec?

From my knowledge, RPKI validators support BGPsec only in the form of router certificates (https://datatracker.ietf.org/doc/html/rfc8210#section-5.10) -- exactly the type of objects that caused your issue. Currently, there are just a few of these certificates published by any public repositories. So in that sense rpki-prover supports BGPsec.

Another part that is relevant to BGPSec is in SLURM RFC (https://datatracker.ietf.org/doc/html/rfc8416#section-3.4.2) where an RPKI validator is supposed to read a local file with extra configuration that is not published in any public repository. This RFC is also supported by rpki-prover, so it's possible to prepare a SLURM file with BGPSec keys and point rpki-prover to it using `--local-exceptions` option.

**Comment by rencarlo014** [comment]
> From my knowledge, RPKI validators support BGPsec only in the form of router certificates (https://datatracker.ietf.org/doc/html/rfc8210#section-5.10) -- exactly the type of objects that caused your issue. Currently, there are just a few of these certificates published by any public repositories. So in that sense rpki-prover supports BGPsec.

Based on the link you've shared, it means that the IOS-XR router does not support BGPsec as IOS-XR only supports RTRv0, hence, Router Key is not used on the communication.

> Another part that is relevant to BGPSec is in SLURM RFC (https://datatracker.ietf.org/doc/html/rfc8416#section-3.4.2) where an RPKI validator is supposed to read a local file with extra configuration that is not published in any public repository. This RFC is also supported by rpki-prover, so it's possible to prepare a SLURM file with BGPSec keys and point rpki-prover to it using `--local-exceptions` option.

Thank you for this, @lolepezy. Will do further research regarding on this one.

Regards,
Ren

**Comment by lolepezy** [comment]
> Based on the link you've shared, it means that the IOS-XR router does not support BGPsec as IOS-XR only supports RTRv0, hence, Router Key is not used on the communication.

That is my understanding as well.
